variables:
  PNAME: $CI_PROJECT_NAME
  SERVER_ADDRESS: 172.16.160.177
  SERVER_SSH_PORT: 9080
  REGISTRY_ADDRESS: 172.16.160.177
  REGISTRY_PORT: 5000

image: $REGISTRY_ADDRESS:$REGISTRY_PORT/docker_stable_ssh:latest

services:
  - $REGISTRY_ADDRESS:$REGISTRY_PORT/docker_dind_ssh

stages:
  - build
  - build_image
#  - update

before_script:
  - mkdir /root/.ssh
  - cp id_rsa /root/.ssh/id_rsa
  - cp id_rsa.pub /root/.ssh/id_rsa.pub
  - chmod 600 /root/.ssh/id_rsa

BuildSite:
  stage: build
  image: $REGISTRY_ADDRESS:$REGISTRY_PORT/node8.16.0:latest
  script:
    - scp -P $SERVER_SSH_PORT -o stricthostkeychecking=no root@$SERVER_ADDRESS:/root/runner_file_temp/$PNAME-node-modules.tar.gz ./  || true
    - tar zxvf $PNAME-node-modules.tar.gz > ./null || true
    - npm config set registry https://registry.npm.taobao.org && npm install
    - tar zcvf $PNAME-node-modules.tar.gz node_modules package-lock.json > ./null || true
    - scp -P $SERVER_SSH_PORT -o stricthostkeychecking=no $PNAME-node-modules.tar.gz root@$SERVER_ADDRESS:/root/runner_file_temp/$PNAME-node-modules.tar.gz
    - npm run build
    - tar zcvf $PNAME-dist.tar.gz dist > ./null
    - scp -P $SERVER_SSH_PORT -o stricthostkeychecking=no $PNAME-dist.tar.gz root@$SERVER_ADDRESS:/root/runner_file_temp/$PNAME-dist.tar.gz
  tags:
    - temp_rhbj

BuildImage:
  stage: build_image
  script:
    - scp -P $SERVER_SSH_PORT -o stricthostkeychecking=no root@$SERVER_ADDRESS:/root/runner_file_temp/$PNAME-dist.tar.gz ./
    - tar zxvf $PNAME-dist.tar.gz > ./null || true
    - docker build -t $REGISTRY_ADDRESS:$REGISTRY_PORT/$PNAME:latest .
    - docker push $REGISTRY_ADDRESS:$REGISTRY_PORT/$PNAME:latest
    - ssh -p $SERVER_SSH_PORT -o stricthostkeychecking=no root@$SERVER_ADDRESS "/root/deploy_script/projects/$PNAME/update_service.sh"
  tags:
    - temp_rhbj
